### ISSUE TITLE
unlock mutex of condition variable before notify may improve the performance

### ISSUE THREAD

**Issue by linhaigoo** [LegendJohna/SigSlot#2]
https://stackoverflow.com/questions/17101922/do-i-have-to-acquire-lock-before-calling-condition-variable-notify-one

**Comment by LegendJohna** [comment]
Thank you for your advice, I have modified the code so that the mutex will unlock before condition variable is notified ,If you have any other problem ,feel free to communicate

**Comment by LegendJohna** [comment]
fixed
